#!/usr/bin/env bash
set -euo pipefail

die() {
  echo "error: $*" >&2
  exit 1
}

info() {
  echo "==> $*"
}

if [ "$(id -u)" -ne 0 ]; then
  die "Run this with sudo: sudo bash ./install-linux.sh"
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=linux/omen-boot-lib.sh
. "$SCRIPT_DIR/linux/omen-boot-lib.sh"

ACTION="install"
ACPI_S5=0
for arg in "$@"; do
  case "$arg" in
    --acpi-s5) ACPI_S5=1 ;;
    remove|uninstall|install) ACTION="$arg" ;;
    *) die "Unknown argument: $arg (use install, remove, and optional --acpi-s5)" ;;
  esac
done
SYSTEMCTL_PATH="$(command -v systemctl || die "systemctl command not found")"
GSETTINGS_PATH="$(command -v gsettings || true)"

CURRENT_USER="${SUDO_USER:-}"
if [ -z "$CURRENT_USER" ] || [ "$CURRENT_USER" = "root" ]; then
  CURRENT_USER="${LOGNAME:-}"
  if [ "$CURRENT_USER" = "root" ] || [ -z "$CURRENT_USER" ]; then
    CURRENT_USER="$(logname 2>/dev/null || true)"
  fi
fi

CURRENT_HOME=""
if [ -n "$CURRENT_USER" ] && [ "$CURRENT_USER" != "root" ]; then
  CURRENT_HOME="$(getent passwd "$CURRENT_USER" | cut -d: -f6 || true)"
fi

KEYBINDING_NAME="OMEN Clean Shutdown"
KEYBINDING_COMMAND="/usr/local/bin/omen-clean-shutdown-launcher"
KEYBINDING_KEY="XF86Launch2"
KEYBINDING_PATH=""

source /etc/os-release 2>/dev/null || true
if [ "${ID:-}" != "fedora" ] && [[ "${ID_LIKE:-}" != *fedora* ]] && \
   [ "${ID:-}" != "cachyos" ] && [ "${ID:-}" != "arch" ] && [[ "${ID_LIKE:-}" != *arch* ]]; then
  info "This installer is written for Fedora/Nobara and Arch/CachyOS, but will keep going."
fi

EFI_MOUNTED_BY_SCRIPT=0

ensure_linux_efi_mounted() {
  EFI_MOUNT="$(detect_linux_efi_mount)"
  if findmnt -n -o TARGET "$EFI_MOUNT" >/dev/null 2>&1 || mountpoint -q "$EFI_MOUNT" 2>/dev/null; then
    info "Linux EFI/boot mount already at $EFI_MOUNT"
    return 0
  fi

  local efi_part=""
  efi_part="$(list_esp_devs | head -n1 || true)"
  if [ -n "$efi_part" ]; then
    local existing_target
    existing_target="$(mounted_target "$efi_part")"
    if [ -n "$existing_target" ]; then
      EFI_MOUNT="$existing_target"
      info "EFI partition $efi_part is already mounted at $EFI_MOUNT"
      return 0
    fi
  fi

  if [ -z "$efi_part" ]; then
    info "No ESP found to auto-mount; continuing with $EFI_MOUNT"
    return 0
  fi

  info "Mounting EFI partition $efi_part at $EFI_MOUNT..."
  mkdir -p "$EFI_MOUNT"
  if mount "$efi_part" "$EFI_MOUNT"; then
    EFI_MOUNTED_BY_SCRIPT=1
  else
    info "Could not mount $efi_part at $EFI_MOUNT; continuing"
  fi
}

write_env_file() {
  local path="$OMEN_ENV_FILE"
  cat >"$path" <<EOF
# Generated by install-linux.sh. Sourced by omen-clean-shutdown.sh.
BOOTLOADER="${BOOTLOADER}"
ONESHOT_METHOD="${ONESHOT_METHOD}"
WINDOWS_ESP_DEV="${WINDOWS_ESP_DEV:-}"
WINDOWS_BOOTNUM="${WINDOWS_BOOTNUM:-}"
EFI_MOUNT="${EFI_MOUNT:-}"
LIMINE_CONF="${LIMINE_CONF:-}"
LIMINE_WINDOWS_ENTRY="${LIMINE_WINDOWS_ENTRY:-}"
GRUB_CFG="${GRUB_CFG:-}"
GRUB_WINDOWS_ENTRY="${GRUB_WINDOWS_ENTRY:-}"
REFIND_CONF="${REFIND_CONF:-}"
REFIND_SOURCE="${REFIND_SOURCE:-}"
REFIND_TARGET="${REFIND_TARGET:-}"
FLAG_FILE="${FLAG_FILE:-}"
RESTORE_FILE="${RESTORE_FILE:-}"
EOF
  chmod 0644 "$path"
}

detect_keybinding() {
  local key_line=""

  if [ -t 0 ] && command -v libinput >/dev/null 2>&1 && command -v timeout >/dev/null 2>&1; then
    info "Press Enter, then press the Copilot/AI button once within 8 seconds."
    read -r _ || true
    key_line="$(timeout 8s sh -c 'libinput debug-events 2>&1' | grep -m1 -o 'KEY_PROG[1-4]' || true)"
    case "$key_line" in
      KEY_PROG1) KEYBINDING_KEY="XF86Launch1" ;;
      KEY_PROG2) KEYBINDING_KEY="XF86Launch2" ;;
      KEY_PROG3) KEYBINDING_KEY="XF86Launch3" ;;
      KEY_PROG4) KEYBINDING_KEY="XF86Launch4" ;;
      *) KEYBINDING_KEY="XF86Launch2" ;;
    esac
    info "Detected $key_line; using binding key $KEYBINDING_KEY."
  else
    info "Using default binding key $KEYBINDING_KEY."
  fi
}

install_files() {
  ensure_linux_efi_mounted

  BOOTLOADER="$(detect_bootloader "$EFI_MOUNT")"
  LIMINE_CONF="$(find_limine_conf "$EFI_MOUNT" || true)"
  GRUB_CFG="$(find_grub_cfg || true)"
  REFIND_CONF="$(find_refind_conf_in "$EFI_MOUNT" || true)"
  REFIND_SOURCE="$(find_refind_source_in "$EFI_MOUNT" || true)"
  WINDOWS_ESP_DEV="$(detect_windows_esp_dev || true)"
  WINDOWS_BOOTNUM="$(detect_windows_bootnum || true)"
  LIMINE_WINDOWS_ENTRY="$(limine_windows_entry "$EFI_MOUNT" || true)"
  GRUB_WINDOWS_ENTRY="$(grub_windows_entry || true)"
  ONESHOT_METHOD="$(choose_oneshot_method "$BOOTLOADER" "$WINDOWS_BOOTNUM")"

  # Do not bake a transient /run mount path into FLAG_FILE. Runtime remounts the Windows ESP.
  if [ -n "$WINDOWS_ESP_DEV" ]; then
    local win_root
    win_root="$(ensure_windows_esp_mounted_rw "$WINDOWS_ESP_DEV" || true)"
    if [ -n "$win_root" ]; then
      mkdir -p "$win_root/EFI/omen"
      info "Windows ESP writable at $win_root (flag will be $OMEN_FLAG_RELPATH)"
    fi
  fi
  FLAG_FILE="${FLAG_FILE:-}"

  if [ -n "$REFIND_CONF" ]; then
    RESTORE_FILE="$(dirname "$REFIND_CONF")/default_selection_restore"
    REFIND_TARGET="${REFIND_TARGET:-$EFI_MOUNT/EFI/Microsoft/Boot/bootmgfw.efi}"
  else
    RESTORE_FILE=""
    REFIND_TARGET="${REFIND_TARGET:-}"
  fi

  info "Detected bootloader: $BOOTLOADER"
  info "One-shot method: $ONESHOT_METHOD"
  [ -n "$WINDOWS_ESP_DEV" ] && info "Windows ESP: $WINDOWS_ESP_DEV" || info "Windows ESP: not found (will retry at shutdown)"
  [ -n "$WINDOWS_BOOTNUM" ] && info "Windows Boot Manager: Boot$WINDOWS_BOOTNUM" || info "Windows Boot Manager NVRAM entry: not found"
  [ -n "$LIMINE_CONF" ] && info "Limine config: $LIMINE_CONF"
  [ -n "$GRUB_CFG" ] && info "GRUB config: $GRUB_CFG"
  [ -n "$REFIND_CONF" ] && info "rEFInd config: $REFIND_CONF"
  info "/ fstype: $(fstype_of_path / || echo unknown)  /boot fstype: $(fstype_of_path /boot || echo unknown)"

  if [ "$BOOTLOADER" = "unknown" ] && [ -z "$WINDOWS_BOOTNUM" ] && [ -z "$REFIND_CONF" ]; then
    die "Could not detect Limine, GRUB, rEFInd, or a Windows Boot Manager EFI entry. Set BOOTLOADER and WINDOWS_BOOTNUM."
  fi

  if [ "$BOOTLOADER" = "grub" ] && ! grubenv_is_writable_at_boot; then
    info "GRUB env is on $(fstype_of_path "$(dirname "$(grubenv_path || echo /boot)")" || echo unknown); using BootNext instead of grub-reboot (avoids a Btrfs Windows boot loop)."
  fi

  write_env_file

  info "Installing helper scripts..."
  mkdir -p /usr/local/lib/omen-clean-shutdown
  install -m 0644 "$SCRIPT_DIR/linux/omen-boot-lib.sh" /usr/local/lib/omen-clean-shutdown/omen-boot-lib.sh
  install -m 0755 "$SCRIPT_DIR/linux/omen-clean-shutdown.sh" /usr/local/bin/omen-clean-shutdown.sh
  install -m 0755 "$SCRIPT_DIR/linux/refind-protect.sh" /usr/local/bin/refind-protect.sh
  if [ -f "$SCRIPT_DIR/linux/omen-shutdown-diagnose.sh" ]; then
    install -m 0755 "$SCRIPT_DIR/linux/omen-shutdown-diagnose.sh" /usr/local/bin/omen-shutdown-diagnose
  fi

  cat >/usr/local/bin/omen-clean-shutdown-launcher <<EOF
#!/usr/bin/env bash
set -euo pipefail

confirm_shutdown() {
  if command -v kdialog >/dev/null 2>&1; then
    kdialog --title "Confirm Shutdown" --yesno "Shut down the laptop using the Windows workaround?"
    return \$?
  elif command -v zenity >/dev/null 2>&1; then
    zenity --question --title="Confirm Shutdown" --text="Shut down the laptop using the Windows workaround?"
    return \$?
  elif command -v yad >/dev/null 2>&1; then
    yad --image=dialog-question --title="Confirm Shutdown" --text="Shut down the laptop using the Windows workaround?" --button=Yes:0 --button=No:1
    return \$?
  fi
  echo "No dialog tool found (kdialog, zenity, or yad); proceeding without confirmation." >&2
  return 0
}

if ! confirm_shutdown; then
  exit 0
fi

exec sudo "$SYSTEMCTL_PATH" start omen-clean-shutdown.service
EOF
  chmod 0755 /usr/local/bin/omen-clean-shutdown-launcher

  cat >/usr/share/applications/omen-clean-shutdown.desktop <<EOF
[Desktop Entry]
Type=Application
Name=OMEN Clean Shutdown
Comment=Shut down HP OMEN laptop cleanly via Windows workaround
Exec=/usr/local/bin/omen-clean-shutdown-launcher
Icon=system-shutdown
Categories=System;Utility;
Terminal=false
X-KDE-Shortcuts=$KEYBINDING_KEY
EOF
  chmod 0644 /usr/share/applications/omen-clean-shutdown.desktop

  cat >/etc/systemd/system/omen-clean-shutdown.service <<'EOF'
[Unit]
Description=OMEN clean shutdown via Windows
DefaultDependencies=no
# Do not Conflicts=reboot.target. This unit converts poweroff into reboot
# (BootNext → Windows → S5). A Conflicts= line deadlocks: reboot.target
# waits to stop this service, while ExecStart waits for reboot.target.
Before=poweroff.target halt.target shutdown.target
ConditionPathExists=!/etc/omen-native-poweroff

[Service]
Type=oneshot
ExecStart=/usr/local/bin/omen-clean-shutdown.sh
# RemainAfterExit would keep the unit "active" and skip SuccessAction
# (that hook runs when the unit *stops* successfully).
KillMode=none
TimeoutStartSec=90
SuccessAction=reboot

[Install]
WantedBy=poweroff.target halt.target
EOF

  mkdir -p /etc/systemd/system/poweroff.target.d
  cat >/etc/systemd/system/poweroff.target.d/omen-clean-shutdown.conf <<'EOF'
[Unit]
Wants=omen-clean-shutdown.service
After=omen-clean-shutdown.service
EOF

  mkdir -p /etc/systemd/system/halt.target.d
  cat >/etc/systemd/system/halt.target.d/omen-clean-shutdown.conf <<'EOF'
[Unit]
Wants=omen-clean-shutdown.service
After=omen-clean-shutdown.service
EOF

  cat >/etc/systemd/system/refind-protect.service <<'EOF'
[Unit]
Description=Restore rEFInd if Windows overwrites the boot manager
DefaultDependencies=no
After=local-fs.target

[Service]
Type=oneshot
ExecStart=/usr/local/bin/refind-protect.sh

[Install]
WantedBy=sysinit.target
EOF

  if [ -n "$CURRENT_USER" ] && [ "$CURRENT_USER" != "root" ]; then
    info "Creating sudoers rule for $CURRENT_USER..."
    cat >/etc/sudoers.d/omen-clean-shutdown <<EOF
$CURRENT_USER ALL=(root) NOPASSWD: $SYSTEMCTL_PATH start omen-clean-shutdown.service
Defaults:$CURRENT_USER !requiretty
EOF
    chmod 0440 /etc/sudoers.d/omen-clean-shutdown
    if command -v visudo >/dev/null 2>&1; then
      visudo -cf /etc/sudoers.d/omen-clean-shutdown >/dev/null
    fi
  fi

  mkdir -p /usr/local/share/omen-clean-shutdown
  if [ -f "$SCRIPT_DIR/acpi/ssdt-omen-s5.asl" ]; then
    install -m 0644 "$SCRIPT_DIR/acpi/ssdt-omen-s5.asl" /usr/local/share/omen-clean-shutdown/ssdt-omen-s5.asl
  fi

  systemctl daemon-reload
  systemctl enable omen-clean-shutdown.service >/dev/null
  if [ "$BOOTLOADER" = "refind" ] && [ -n "$REFIND_SOURCE" ]; then
    systemctl enable refind-protect.service >/dev/null
    info "Enabled rEFInd protect service."
  else
    systemctl disable refind-protect.service >/dev/null 2>&1 || true
    info "Skipping rEFInd protect service ($BOOTLOADER)."
  fi

  if [ "$ACPI_S5" -eq 1 ]; then
    info "Experimental ACPI S5 template installed to /usr/local/share/omen-clean-shutdown/ssdt-omen-s5.asl"
    info "This does NOT load AML automatically. Dump your DSDT, confirm PG00/GPTS paths, compile with iasl,"
    info "and add a second bootloader entry. Keep the Windows-reboot workaround until S5 is proven (LED off, chassis cold)."
    info "See README and https://github.com/paolo-de-marinis/omen-acpi/releases/tag/v2.2.0"
  fi

  detect_keybinding

  if [ -n "$GSETTINGS_PATH" ] && [ -n "$CURRENT_USER" ] && [ "$CURRENT_USER" != "root" ]; then
    info "Trying to bind key in GNOME (without replacing existing custom shortcuts)..."
    existing_raw="$(sudo -u "$CURRENT_USER" dbus-run-session -- gsettings get org.gnome.settings-daemon.plugins.media-keys custom-keybindings 2>/dev/null || echo '@as []')"
    n=0
    while printf '%s' "$existing_raw" | grep -q "custom${n}/"; do
      n=$((n + 1))
      if [ "$n" -gt 32 ]; then
        break
      fi
    done
    KEYBINDING_PATH="/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom${n}/"
    if printf '%s' "$existing_raw" | grep -q '@as \[\]' || [ "$existing_raw" = "[]" ]; then
      listed="['$KEYBINDING_PATH']"
    else
      listed="$(printf '%s' "$existing_raw" | sed "s|]$|, '$KEYBINDING_PATH']|")"
    fi
    if sudo -u "$CURRENT_USER" dbus-run-session -- sh -c "
      gsettings set org.gnome.settings-daemon.plugins.media-keys custom-keybindings \"$listed\" &&
      gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:$KEYBINDING_PATH name '$KEYBINDING_NAME' &&
      gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:$KEYBINDING_PATH command '$KEYBINDING_COMMAND' &&
      gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:$KEYBINDING_PATH binding '$KEYBINDING_KEY'
    " >/dev/null 2>&1; then
      info "GNOME keybinding created at $KEYBINDING_PATH for $KEYBINDING_KEY."
    fi
  fi

  if [ -n "$CURRENT_USER" ] && [ "$CURRENT_USER" != "root" ] && [ -n "$CURRENT_HOME" ]; then
    if command -v kwriteconfig6 >/dev/null 2>&1; then
      info "Configuring KDE Plasma 6 shortcut for $CURRENT_USER..."
      sudo -u "$CURRENT_USER" kwriteconfig6 --file "$CURRENT_HOME/.config/kglobalshortcutsrc" --group "services" --key "omen-clean-shutdown.desktop" "_launch=$KEYBINDING_KEY,none,OMEN Clean Shutdown" || true
    elif command -v kwriteconfig5 >/dev/null 2>&1; then
      info "Configuring KDE Plasma 5 shortcut for $CURRENT_USER..."
      sudo -u "$CURRENT_USER" kwriteconfig5 --file "$CURRENT_HOME/.config/kglobalshortcutsrc" --group "services" --key "omen-clean-shutdown.desktop" "_launch=$KEYBINDING_KEY,none,OMEN Clean Shutdown" || true
    fi
  fi

  info "Installed successfully."
  echo
  echo "Bootloader: $BOOTLOADER"
  echo "One-shot Windows boot: $ONESHOT_METHOD"
  echo "You can launch OMEN Clean Shutdown using:"
  echo "  1. App launcher menu: search for 'OMEN Clean Shutdown'"
  echo "  2. Launcher command: omen-clean-shutdown-launcher"
  echo "  3. Keybinding ($KEYBINDING_KEY)"
  echo "  4. Desktop/session Shut Down and systemctl poweroff (intercepted)"
  echo
  echo "Escape hatch (real firmware poweroff, may leave dGPU rail on):"
  echo "  sudo touch /etc/omen-native-poweroff"
  echo "Logs: /var/log/omen-clean-shutdown.log"
  echo "Diagnose: sudo omen-shutdown-diagnose"
  echo
}

remove_files() {
  info "Removing helper files..."
  ensure_linux_efi_mounted
  if [ -f "$OMEN_ENV_FILE" ]; then
    # shellcheck disable=SC1090
    . "$OMEN_ENV_FILE"
  fi
  systemctl stop omen-clean-shutdown.service 2>/dev/null || true
  systemctl disable omen-clean-shutdown.service 2>/dev/null || true
  systemctl disable refind-protect.service 2>/dev/null || true
  rm -f /usr/local/bin/omen-clean-shutdown.sh
  rm -f /usr/local/bin/omen-clean-shutdown-launcher
  rm -f /usr/local/bin/refind-protect.sh
  rm -f /usr/local/bin/omen-shutdown-diagnose
  rm -rf /usr/local/lib/omen-clean-shutdown
  rm -f /usr/share/applications/omen-clean-shutdown.desktop
  rm -f /etc/systemd/system/omen-clean-shutdown.service
  rm -f /etc/systemd/system/refind-protect.service
  rm -f /etc/systemd/system/poweroff.target.d/omen-clean-shutdown.conf
  rmdir /etc/systemd/system/poweroff.target.d 2>/dev/null || true
  rm -f /etc/systemd/system/halt.target.d/omen-clean-shutdown.conf
  rmdir /etc/systemd/system/halt.target.d 2>/dev/null || true
  rm -f /etc/sudoers.d/omen-clean-shutdown
  rm -rf /usr/local/share/omen-clean-shutdown
  if [ -n "${REFIND_CONF:-}" ] && [ -f "${REFIND_CONF}.bak" ]; then
    cp -f "${REFIND_CONF}.bak" "$REFIND_CONF"
  fi
  rm -f "$OMEN_ENV_FILE"
  if [ -n "${FLAG_FILE:-}" ]; then
    rm -f "$FLAG_FILE"
    rmdir "$(dirname "$FLAG_FILE")" 2>/dev/null || true
  fi
  if [ -n "${RESTORE_FILE:-}" ]; then
    rm -f "$RESTORE_FILE" "${RESTORE_FILE}_timeout"
  fi
  systemctl daemon-reload
  info "Removed successfully."
}

case "$ACTION" in
  install)
    install_files
    ;;
  remove|uninstall)
    remove_files
    ;;
  *)
    die "Unknown action: $ACTION (use install or remove)"
    ;;
esac
